services:
  - type: web
    name: gallery-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: gallery-db
          property: connectionString
    plan: free
    numInstances: 1
    region: oregon
    healthCheckPath: /